# Generated by Django 5.2.13 on 2026-08-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por kg')),
                ('estimated_days', models.PositiveSmallIntegerField(default=1, verbose_name='Días estimados')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
