# Generated by Django 5.2.13 on 2026-08-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='Emoji')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicio',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='servicetype',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso máximo (kg)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='min_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso mínimo (kg)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='unit',
            field=models.CharField(choices=[('kg', 'Por kg'), ('piece', 'Por pieza')], default='kg', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por kg/pieza'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='pricing.servicecategory', verbose_name='Categoría'),
        ),
    ]
