# Generated by Django 5.2.13 on 2026-08-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cajero / Recepción'), ('admin', 'Administrador')], default='cashier', max_length=20, verbose_name='Rol'),
        ),
    ]
