# Generated by Django 5.2.13 on 2026-08-05 23:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('ready_to_wash', 'Listo para lavar'), ('on_wash', 'En lavado'), ('ready_to_delivery', 'Listo para entrega'), ('delivered', 'Entregado'), ('completed', 'Completado')], default='received', max_length=20, verbose_name='Estado')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Peso total (kg)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal')),
                ('promised_at', models.DateField(blank=True, null=True, verbose_name='Fecha prometida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por kg')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='Orden')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Línea de orden',
                'verbose_name_plural': 'Líneas de orden',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], max_length=10, verbose_name='Método')),
                ('payment_type', models.CharField(choices=[('advance', 'Anticipo'), ('partial', 'Abono'), ('final', 'Liquidación')], max_length=10, verbose_name='Tipo')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Orden')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('received_at',),
            },
        ),
    ]
