# Generated by Django 5.2.13 on 2026-08-07 21:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Por kg'), ('piece', 'Por pieza')], max_length=10, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Peso (kg)'),
        ),
    ]
